=== UrielSaMo/tecweb/practicas/p12/spotify_v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:complexType name="cuentaType">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="correo" type="xs:string"/>
            <xs:element name="telefono">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="tipo" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="plan" type="xs:string"/>
        <xs:attribute name="fechaIni" type="xs:string"/>
        <xs:attribute name="fechaFin" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="spotifyType">
        <xs:sequence>
            <xs:element name="cuenta" type="cuentaType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="spotify" type="spotifyType"/>
</xs:schema>

=== UrielSaMo/tecweb/practicas/p12/spotify.xml
<?xml version="1.0" encoding="UTF-8"?>
<spotify xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="spotify_v2.xsd">
    <cuenta id="1" plan="premium" fechaIni="21-11-2023" fechaFin="21-12-2023">
        <nombre>Uriel Salinas Morales</nombre>
        <correo>uriel@gmail.com</correo>
        <telefono tipo="movil">2214054360</telefono>
    </cuenta>
    <cuenta id="2" plan="gratuito" fechaIni="21-11-2023" fechaFin="21-03-2024">
        <nombre>Axel Samuel Luna Gomez</nombre>
        <correo>axel@gmail.com</correo>
        <telefono tipo="movil">2222164863</telefono>
    </cuenta>
</spotify>
